---
# tasks file for apache
- name: start service
  service:
    name: httpd
    state: started
    enabled: true
- name: enable firewall
  ansible.posix.firewalld:
    service: http
    state: enabled
    immediate: true
    permanent: true
- name: default html
  template:
    src: template/index.html.j2
    dest: /var/www/html/index.html
