---
- hosts: all
  become: true
  tasks:
  - yum_repository:
      name: baseos
      description: 'RH294 Desc'
      baseurl: http://sample.com
      gpgcheck: true
      gpgkey: http://sample.com
      enabled: false

  - yum_repository:
      name: appstream
      description: 'RH294 Desc'
      baseurl: http://sample.com
      gpgcheck: true
      gpgkey: http://sample.com
      enabled: false
