---
- hosts: all
  become: true
  vars_files:
    - user_list.yml
    - vault.yml
  tasks:
    - name: create groups
      group:
       name: "{{ item }}"
       state: present
      loop:
        - devops
        - opsmgr
    - name: create user
      user:
        name: "{{item.name}}"
        state: present
        groups: devops
        password: "{{ dev_pass | password_hash ('sha512')}}"
      loop: "{{user}}"
      when: 
        - (inventory_hostname in groups['dev'] or inventory_hostname in groups['test'])
        - item.job == "developer"
    - name: create user
      user:
        name: "{{item.name}}"
        state: present
        groups: opsmgr
        password: "{{ mgr_pass | password_hash ('sha512')}}"
      loop: "{{user}}"
      when: 
        - inventory_hostname in groups['prod']
        - item.job == "manager"
