---
- hosts: dev
  become: true
  tasks:
  - service:
      name: httpd
      enabled: true
      state: started
  - file:
      path: /webdev
      group: apache
      mode: '2775'
      state: directory
      setype: httpd_sys_content_t
  - file:
      src: /webdev
      dest: /var/www/html/webdev
      state: link
      setype: httpd_sys_content_t
  - copy:
     content: "Development"
     dest: /webdev/index.html
     setype: httpd_sys_content_t
  - ansible.posix.firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled  
